### ISSUE TITLE
SCALA match error when compiling RADish spec

### ISSUE THREAD

**Issue by rniwa** [radlab/SCADS#14]
I encounter a Scala Match error when compiling RADish spec.

**Comment by rniwa** [comment]
scala.MatchError: RECORD
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$.toScalaType(scalagen.scala:310)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$$anonfun$2.apply(scalagen.scala:317)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$$anonfun$2.apply(scalagen.scala:317)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:238)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:238)
    at scala.collection.LinearSeqLike$class.foreach(LinearSeqLike.scala:97)
    at scala.collection.immutable.List.foreach(List.scala:46)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:238)
    at scala.collection.immutable.List.map(List.scala:46)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$.generateQuery(scalagen.scala:317)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$$anonfun$generate$2$$anonfun$apply$1.apply(scalagen.scala:33)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$$anonfun$generate$2$$anonfun$apply$1.apply(scalagen.scala:33)
    at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
    at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:52)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:62)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:62)
    at scala.collection.Iterator$class.foreach(Iterator.scala:582)
    at scala.collection.mutable.HashTable$$anon$1.foreach(HashTable.scala:160)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:193)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:21)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:62)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$$anonfun$generate$2.apply(scalagen.scala:33)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$$anonfun$generate$2.apply(scalagen.scala:33)
    at edu.berkeley.cs.scads.piql.parser.Generator.indent(generator.scala:31)
    at edu.berkeley.cs.scads.piql.parser.Generator.outputCont(generator.scala:54)
    at edu.berkeley.cs.scads.piql.parser.Generator.outputBraced(generator.scala:45)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$.generate(scalagen.scala:32)
    at edu.berkeley.cs.scads.piql.parser.ScalaGen$.generate(scalagen.scala:13)
    at edu.berkeley.cs.scads.piql.parser.Generator.apply(generator.scala:20)
    at edu.berkeley.cs.scads.piql.Compiler$.compileToFile(compiler.scala:66)
    at edu.berkeley.scads.piql.CompilePiqlMojo.execute(CompilePiqlMojo.java:64)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1205)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1033)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:643)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

**Comment by rniwa** [comment]
http://gist.github.com/412348

**Comment by rniwa** [comment]
Reduced query: http://gist.github.com/412369

**Comment by marmbrus** [comment]
This compiles now.
