### ISSUE TITLE
None.get error?

### ISSUE THREAD

**Issue by amfeng** [radlab/SCADS#16]
We're getting these errors when trying to compile the schema (mvn assembly:assembly). Possibly some type of null pointer exception?

INFO] Compiling:gradit_schema.piql
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] None.get
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.util.NoSuchElementException: None.get
       at scala.None$.get(Option.scala:169)
       at scala.None$.get(Option.scala:167)
       at edu.berkeley.cs.scads.piql.parser.Binder$$anonfun$14.apply(bind.scala:335)
       at edu.berkeley.cs.scads.piql.parser.Binder$$anonfun$14.apply(bind.scala:335)
       at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:238)
       at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:238)
       at scala.collection.LinearSeqLike$class.foreach(LinearSeqLike.scala:97)
       at scala.collection.immutable.List.foreach(List.scala:46)
       at scala.collection.TraversableLike$class.map(TraversableLike.scala:238)
       at scala.collection.immutable.List.map(List.scala:46)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:335)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:316)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bindEntities(bind.scala:364)
       at edu.berkeley.cs.scads.piql.parser.Binder.bind(bind.scala:43)
       at edu.berkeley.cs.scads.piql.Compiler$.compileToFile(compiler.scala:63)
       at edu.berkeley.scads.piql.CompilePiqlMojo.execute(CompilePiqlMojo.java:39)
       at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1205)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1033)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:643)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
       at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
       at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:616)
       at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
       at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
       at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
       at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

**Comment by marmbrus** [comment]
Copy of the spec that is causing the issue?  Why don't you post it as a gist (gist.github.com)...

**Comment by amfeng** [comment]
http://gist.github.com/412553

**Comment by marmbrus** [comment]
The compiler should now print out a more helpful error message: "[FATAL scads.binding] bind.scala:348(findKeyAttribute$1) Unknown attribute 'user_id'referenced in primary key for entity game_players"
