### ISSUE TITLE
Scala console crashed because Utf8 cannot be casted to java.lang.String

### ISSUE THREAD

**Issue by rniwa** [radlab/SCADS#20]
Get the following error for the query:

QUERY userByEmail
FETCH User
WHERE email = [1:addr]
LIMIT 10 MAX 100

scala> Queries.userByEmail("a@com")
java.lang.ClassCastException: org.apache.avro.util.Utf8 cannot be cast to java.lang.String
    at piql.User$idxUseremail_.put(radish3.scala:2015)
    at edu.berkeley.cs.scads.storage.Namespace$$anonfun$minRecord$1.apply(ScadsCluster.scala:605)
    at edu.berkeley.cs.scads.storage.Namespace$$anonfun$minRecord$1.apply(ScadsCluster.scala:553)
    at scala.collection.immutable.Range$ByOne$class.foreach(Range.scala:171)
    at scala.collection.immutable.Range$$anon$1.foreach(Range.scala:164)
    at edu.berkeley.cs.scads.storage.Namespace.minRecord(ScadsCluster.scala:553)
    at edu.berkeley.cs.scads.storage.Namespace.getPrefix(ScadsCluster.scala:632)
    at edu.berkeley.cs.scads.storage.Namespace.getPrefix(ScadsCluster.scala:619)
    at edu.berkeley.cs.scads.piql.QueryExecutor$class.prefixGet(queryexecution.scala:79)
    at piql.Queries$.prefixGet(radish3.scala:2028)
    at piql.Queries$.userByEmail(radish3.scala:2034)
    at .<init>(<console>:9)
    at .<clinit>(<console>)
    at RequestResult$.<init>(<console>:4)
    at RequestResult$.<clinit>(<console>)
    at RequestResult$scala_repl_result(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at scala.tools.nsc.Interpreter$Request$$anonfun$loadAndRun$1$$anonfun$apply$13.apply(Interpreter.scala:827)
    at scala.tools.nsc.Interpreter$Request$$anonfun$loadAndRun$1$$anonfun$apply$13.apply(Interpreter.scala:827)
    at scala.util.control.Exception$Catch.apply(Exception.scala:79)
    at scala.tools.nsc.Interpreter$Request$$anonfun$loadAndRun$1.apply(Interpreter.scala:826)
    at scala.tools.nsc.Interpreter$Request$$anonfun$loadAndRun$1.apply(Interpreter.scala:826)
    at scala.util.control.Exception$Catch.apply(Exception.scala:79)
    at scala.tools.nsc.Interpreter$Request.loadAndRun(Interpreter.scala:825)
    at scala.tools.nsc.Interpreter.interpret(Interpreter.scala:467)
    at scala.tools.nsc.Interpreter.interpret(Interpreter.scala:457)
    at scala.tools.nsc.InterpreterLoop.interpretStartingWith(InterpreterLoop.scala:391)
    at scala.tools.nsc.InterpreterLoop.command(InterpreterLoop.scala:367)
    at scala.tools.nsc.InterpreterLoop.processLine$1(InterpreterLoop.scala:249)
    at scala.tools.nsc.InterpreterLoop.repl(InterpreterLoop.scala:267)
    at...

**Comment by stephentu** [comment]
fixed
