### ISSUE TITLE
QuorumProtSpec does not initialize properly

### ISSUE THREAD

**Issue by stephentu** [radlab/SCADS#23]
I'm getting this error with QuorumProtSpec:

---
## Test set: edu.berkeley.cs.scads.test.QuorumProtSpec

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.026 sec <<< FAILURE!
initializationError(edu.berkeley.cs.scads.test.QuorumProtSpec)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.ClassCastException
  at edu.berkeley.cs.scads.test.QuorumProtSpec.<init>(QuorumProtSpec.scala:16)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
  at java.lang.Class.newInstance0(Class.java:355)
  at java.lang.Class.newInstance(Class.java:308)
  at org.scalatest.junit.JUnitRunner.<init>(JUnitRunner.scala:62)
[...]

which deals with this initialization:

  MessageHandlerFactory.creatorFn = () => new TestMessageHandler()

  val messageHandler : TestMessageHandler = MessageHandler.instance match {
       case g2: TestMessageHandler => g2
       case _ => throw new ClassCastException
    }  

this kind of initialization code should probably run under an "initialized" block (see the initialized function in http://www.scalatest.org/getting_started_with_junit_4).

**Comment by kraskat** [comment]
So, Stephen is fixing this with the new MessageHandler, right?

**Comment by stephentu** [comment]
ya this particular message is fixed now. Tim- now the QuorumProtSpec is failing assertions in the test case (not related to this message handler issue). can you take a look?

**Comment by kraskat** [comment]
Sure, I do it tomorrow

**Comment by kraskat** [comment]
Looks like a race condition. Probably, Thread.sleep is not sufficient anymore to ensure that all messages are processed before the next steps is executed. Any ideas on how to solve that?

**Comment by kraskat** [comment]
grmpf, no race condition. There was a bug in one of the failure cases. Is fixed and submitted.
