### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by kraskat** [radlab/SCADS#24]
Sometimes QuorumProtSpec throws an TimeoutException. Any idea why?:
- should read repair range requests **\* FAILED ***
  edu.berkeley.cs.scads.comm.TimeoutException
  at edu.berkeley.cs.scads.comm.RemoteActorProxy$class.$bang$qmark(Actors.scala:80)
  at edu.berkeley.cs.scads.comm.PartitionService.$bang$qmark(Actors.scala:35)
  at edu.berkeley.cs.scads.storage.QuorumProtocol$$anonfun$getAllVersions$1.apply(QuorumProtocol.scala:83)
  at edu.berkeley.cs.scads.storage.QuorumProtocol$$anonfun$getAllVersions$1.apply(QuorumProtocol.scala:82)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
  at scala.collection.immutable.List.foreach(List.scala:45)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
  at scala.collection.immutable.List.map(List.scala:45)
  at edu.berkeley.cs.scads.storage.QuorumProtocol.getAllVersions(QuorumProtocol.scala:82)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.getAllVersions(QuorumProtSpec.scala:36)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$10$$anonfun$4.apply(QuorumProtSpec.scala:156)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$10$$anonfun$4.apply(QuorumProtSpec.scala:156)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
  at scala.collection.immutable.Range$ByOne$class.foreach(Range.scala:282)
  at scala.collection.immutable.Range$$anon$1.foreach(Range.scala:274)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:227)
  at scala.collection.immutable.Range.flatMap(Range.scala:39)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$10.apply(QuorumProtSpec.scala:156)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$10.apply(QuorumProtSpec.scala:148)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.withBlocker(QuorumProtSpec.scala:76)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(QuorumProtSpec.scala:148)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(QuorumProtSpec.scala:148)
  at edu.berkeley.cs.scads.test.QuorumProtSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(QuorumProtSpec.scala:148)
  at org.scalatest.WordSpec$$anon$3.apply(WordSpec.scala:2122)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1509)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.withFixture(QuorumProtSpec.scala:12)
  at org.scalatest.WordSpec$class.runTest(WordSpec.scala:2119)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.runTest(QuorumProtSpec.scala:12)
  at org.scalatest.WordSpec$$anonfun$org$scalatest$WordSpec$$runTestsInBranch$1.apply(WordSpec.scala:2044)
  at org.scalatest.WordSpec$$anonfun$org$scalatest$WordSpec$$runTestsInBranch$1.apply(WordSpec.scala:2033)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
  at scala.collection.immutable.List.foreach(List.scala:45)
  at org.scalatest.WordSpec$class.org$scalatest$WordSpec$$runTestsInBranch(WordSpec.scala:2032)
  at org.scalatest.WordSpec$$anonfun$org$scalatest$WordSpec$$runTestsInBranch$1.apply(WordSpec.scala:2052)
  at org.scalatest.WordSpec$$anonfun$org$scalatest$WordSpec$$runTestsInBranch$1.apply(WordSpec.scala:2033)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
  at scala.collection.immutable.List.foreach(List.scala:45)
  at org.scalatest.WordSpec$class.org$scalatest$WordSpec$$runTestsInBranch(WordSpec.scala:2032)
  at org.scalatest.WordSpec$class.runTests(WordSpec.scala:2249)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.runTests(QuorumProtSpec.scala:12)
  at org.scalatest.Suite$class.run(Suite.scala:1804)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.org$scalatest$WordSpec$$super$run(QuorumProtSpec.scala:12)
  at org.scalatest.WordSpec$class.run(WordSpec.scala:2320)
  at edu.berkeley.cs.scads.test.QuorumProtSpec.run(QuorumProtSpec.scala:12)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:59)
  at org.scalatest.tools.Runner$$anonfun$doRunRunRunADoRunRun$3.apply(Runner.scala:1523)
  at org.scalatest.tools.Runner$$anonfun$doRunRunRunADoRunRun$3.apply(Runner.scala:1520)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
  at scala.collection.immutable.List.foreach(List.scala:45)
  at org.scalatest.tools.Runner$.doRunRunRunADoRunRun(Runner.scala:1520)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:616)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:615)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1564)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:614)
  at org.scalatest.tools.Runner$.main(Runner.scala:498)
  at org.scalatest.tools.Runner.main(Runner.scala)

**Comment by marmbrus** [comment]
Does this happen deterministically?

**Comment by kraskat** [comment]
Nope! But maybe we can force it within a while-loop
