### ISSUE TITLE
retrieveExternalRecordSchema doesn't handle classes not on the compiler classpath

### ISSUE THREAD

**Issue by marmbrus** [radlab/SCADS#41]
java.lang.ClassNotFoundException: edu.berkeley.cs.scads.comm.Message
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at edu.berkeley.cs.avro.plugin.ScalaAvroPluginComponent$class.retrieveExternalRecordSchema(ScalaAvroPlugin.scala:120)
    at edu.berkeley.cs.avro.plugin.ScalaAvroPlugin$schemaGen$.retrieveExternalRecordSchema(ScalaAvroPlugin.scala:249)
    at edu.berkeley.cs.avro.plugin.SchemaGen$SchemaGenTransformer.edu$berkeley$cs$avro$plugin$SchemaGen$SchemaGenTransformer$$createSchema(SchemaGen.scala:109)
    at edu.berkeley.cs.avro.plugin.SchemaGen$SchemaGenTransformer$$anonfun$4.apply(SchemaGen.scala:135)
    at edu.berkeley.cs.avro.plugin.SchemaGen$SchemaGenTransformer$$anonfun$4.apply(SchemaGen.scala:133)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
    at scala.collection.immutable.List.map(List.scala:45)
    at edu.berkeley.cs.avro.plugin.SchemaGen$SchemaGenTransformer.transform(SchemaGen.scala:133)
    at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:856)
    at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:854)

**Comment by marmbrus** [comment]
This is also causing problems with sbt incremental compilation.  The error occurs anytime dependent avro classes are in different files and only one of them is incrementally recompiled.
